vich_uploader:
    db_driver: orm

    mappings:
        user_avatar:
            uri_prefix:         /uploads/users
            upload_destination: "%kernel.root_dir%/../web/uploads/users"
            namer:              vich_uploader.namer_uniqid
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true

        article_image:
            uri_prefix:         /uploads/articles
            upload_destination: "%kernel.root_dir%/../web/uploads/articles"
            namer:              vich_uploader.namer_uniqid
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true

