services:
    filter.configurator:
        class: AppBundle\Filter\Configurator
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@security.token_storage"
            - "@security.authorization_checker"

        tags:
            - { name: kernel.event_listener, event: kernel.request }

    create_movie_comment_form:
        class: AppBundle\Form\CreateMovieCommentType
        arguments: ["@security.token_storage", "@security.authorization_checker"]
        tags:
            - {name: form.type}
