schema:
    class: AppBundle\Entity\Article
    db_driver: orm
    glavweb_security: false
    properties:
        id: # integer
        type: # ArticleType
        name: # string
        body: # text
        publish: # boolean
        publishAt: # datetime

        movies: # AppBundle\Entity\Movie
            join: left
            properties:
                id: # integer
                name: # string