schema:
    class: AppBundle\Entity\Event
    properties:
        id: # integer
        name: # string

        eventGroup: # AppBundle\Entity\EventGroup
            join: left
            properties:
                id: # integer
                name: # string

        tags: # AppBundle\Entity\Tag
            join: left
            properties:
                id: # integer
                name: # string

        articles: # AppBundle\Entity\Article
            join: left
            properties:
                id: # integer
                type: # ArticleType
                name: # string
                slug: # string
                body: # text
                countEvents: # integer
                publish: # boolean
                image: # string
                updatedAt: # datetime
                publishAt: # datetime

        sessions: # AppBundle\Entity\Session
            join: left
            properties:
                id: # integer
                name: # string

        eventDetail: # AppBundle\Entity\EventDetail
            join: left
            properties:
                id: # integer
                body: # text