schema:
    class: AppBundle\Entity\MovieDetail
    db_driver: orm
    glavweb_security: false
    properties:
        id: # integer
        body: # text

        movie: # AppBundle\Entity\Movie
            join: left
            properties:
                id: # integer
                name: # string