schema:
    class: AppBundle\Entity\MovieSession
    db_driver: orm
    glavweb_security: false
    properties:
        id: # integer
        name: # string

        movie: # AppBundle\Entity\Movie
            join: left
            properties:
                id: # integer
                name: # string