scope:
    id: # integer
    name: # string
    eventGroup: # AppBundle\Entity\EventGroup
        id:
    tags: # AppBundle\Entity\Tag
        id:
    articles: # AppBundle\Entity\Article
        id:
    sessions: # AppBundle\Entity\Session
        id:
    eventDetail: # AppBundle\Entity\EventDetail
        id: